mishael-o/Dapper.SimpleSqlBuilder

- .github/workflows/ci-cd.yml
- README.md
- src/version.json
> First beta release.

- .github/workflows/ci-cd.yml
- src/Builder/Directory.Build.props
- src/Tests/IntegrationTests/SimpleSqlBuilder.IntegrationTests/AssemblyInfo.cs
- src/Tests/IntegrationTests/SimpleSqlBuilder.IntegrationTests/MSSql/MSSqlTests.cs
- src/Tests/IntegrationTests/SimpleSqlBuilder.IntegrationTests/MSSql/MSSqlTestsFixture.cs
- src/Tests/IntegrationTests/SimpleSqlBuilder.IntegrationTests/MySql/MySqlTests.cs
- src/Tests/IntegrationTests/SimpleSqlBuilder.IntegrationTests/MySql/MySqlTestsFixture.cs
- src/Tests/IntegrationTests/SimpleSqlBuilder.IntegrationTests/PostgreSql/PostgreSqlTests.cs
- src/Tests/IntegrationTests/SimpleSqlBuilder.IntegrationTests/PostgreSql/PostgreSqlTestsFixture.cs
- src/version.json
> Integration test and ci-cd improvements and fixes.

- src/version.json
> First major release

- .github/pull_request_template.md
- .github/release.yml
- .github/workflows/ci-cd.yml
- docs/CONTRIBUTING.md
- src/Builder/Directory.Build.props
- src/version.json
Changes: Updated pipeline configuration
Updated documentation to reflect new changes.
Updated NerbandVersioning nuget package
> Updated pipeline configuration

- src/Builder/SimpleSqlBuilder/Core/SimpleBuilder.cs
- src/Builder/SimpleSqlBuilder/Core/SimpleBuilderSettings.cs
- src/Tests/IntegrationTests/SimpleSqlBuilder.IntegrationTests/MSSql/MSSqlTests.cs
- src/Tests/IntegrationTests/SimpleSqlBuilder.IntegrationTests/MySql/MySqlTests.cs
- src/Tests/IntegrationTests/SimpleSqlBuilder.IntegrationTests/PostgreSql/PostgreSqlTests.cs
- src/Tests/UnitTests/SimpleSqlBuilder.DependencyInjection.UnitTests/Extensions/ServiceCollectionExtensionsTests.cs
- src/Tests/UnitTests/SimpleSqlBuilder.UnitTests/Core/SimpleBuilderSettingsTests.cs
- src/Tests/UnitTests/SimpleSqlBuilder.UnitTests/Core/SimpleBuilderTests.cs
- src/Tests/UnitTests/SimpleSqlBuilder.UnitTests/Core/SqlFormatterTests.cs
- src/version.json
Changed `SimpleBuilderSettings` from a static class to a singleton for thread safety and improvements.
Updated unit tests.
Fixed bugs in integration tests.
Bumped major version number.
> SimpleBuilderSettings rewrite for thread safety and optimisations.

- .github/pull_request_template.md
- .github/release.yml
- .github/workflows/ci-cd.yml
- docs/CONTRIBUTING.md
- src/Builder/Directory.Build.props
- src/Builder/SimpleSqlBuilder/Core/SimpleBuilder.cs
- src/Builder/SimpleSqlBuilder/Core/SimpleBuilderSettings.cs
- src/Tests/IntegrationTests/SimpleSqlBuilder.IntegrationTests/MSSql/MSSqlTests.cs
- src/Tests/IntegrationTests/SimpleSqlBuilder.IntegrationTests/MySql/MySqlTests.cs
- src/Tests/IntegrationTests/SimpleSqlBuilder.IntegrationTests/PostgreSql/PostgreSqlTests.cs
- src/Tests/UnitTests/SimpleSqlBuilder.DependencyInjection.UnitTests/Extensions/ServiceCollectionExtensionsTests.cs
- src/Tests/UnitTests/SimpleSqlBuilder.UnitTests/Core/SimpleBuilderSettingsTests.cs
- src/Tests/UnitTests/SimpleSqlBuilder.UnitTests/Core/SimpleBuilderTests.cs
- src/Tests/UnitTests/SimpleSqlBuilder.UnitTests/Core/SqlFormatterTests.cs
- src/version.json
> next release

- src/Builder/Directory.Build.props
Fixed package tags and updated copyright date
> Fixed package tags and updated copyright date

- src/Builder/SimpleSqlBuilder/Core/Builder.cs
- src/Builder/SimpleSqlBuilder/Core/IBuilderFormatter.cs
- src/Builder/SimpleSqlBuilder/FluentBuilder/IFluentSqlBuilder.cs
- src/Tests/IntegrationTests/SimpleSqlBuilder.IntegrationTests/SimpleSqlBuilder.IntegrationTests.csproj
Code clean-up and preparing release build.
> Code clean-up and preparing release build.

- README.md
- src/Builder/SimpleSqlBuilder.DependencyInjection/Core/SimpleBuilderFactory.cs
- src/Builder/SimpleSqlBuilder.DependencyInjection/Core/SimpleBuilderOptions.cs
- src/Tests/UnitTests/SimpleSqlBuilder.DependencyInjection.UnitTests/Core/SimpleBuilderFactoryTests.cs
- src/Tests/UnitTests/SimpleSqlBuilder.DependencyInjection.UnitTests/Core/SimpleBuilderOptionsTests.cs
- src/Tests/UnitTests/SimpleSqlBuilder.DependencyInjection.UnitTests/Extensions/ServiceCollectionExtensionsTests.cs
Added support for reloadable configuration for options in the dependency library.
Updated documentation.
Code clean-up and optimisation.
> Added support for reloadable configuration for options in the dependency library.

- README.md
- docs/CONTRIBUTING.md
- src/.editorconfig
- src/Directory.Build.props
- src/Tests/IntegrationTests/SimpleSqlBuilder.IntegrationTests/MSSql/MSSqlFluentTests.cs
- src/Tests/IntegrationTests/SimpleSqlBuilder.IntegrationTests/Models/CustomId.cs
- src/Tests/IntegrationTests/SimpleSqlBuilder.IntegrationTests/MySql/MySqlFluentTests.cs
- src/Tests/IntegrationTests/SimpleSqlBuilder.IntegrationTests/PostgreSql/PostgreSqlFluentTests.cs
> Documentation update

- .github/workflows/ci-cd.yml
- README.md
- src/.editorconfig
- src/Benchmark/SimpleSqlBuilder.BenchMark/Program.cs
- src/Benchmark/SimpleSqlBuilder.BenchMark/README.md
- src/Benchmark/SimpleSqlBuilder.BenchMark/SimpleSqlBuilder.BenchMark.csproj
- src/Builder/Directory.Build.props
- src/Builder/SimpleSqlBuilder.DependencyInjection/SimpleSqlBuilder.DependencyInjection.csproj
- src/Builder/SimpleSqlBuilder.StrongName/SimpleSqlBuilder.StrongName.csproj
- src/Builder/SimpleSqlBuilder/SimpleSqlBuilder.csproj
- src/Tests/Directory.Build.props
- src/Tests/IntegrationTests/SimpleSqlBuilder.IntegrationTests/MSSql/MSSqlTestsFixture.cs
- src/Tests/IntegrationTests/SimpleSqlBuilder.IntegrationTests/MySql/MySqlTestsFixture.cs
- src/Tests/IntegrationTests/SimpleSqlBuilder.IntegrationTests/PostgreSql/PostgreSqlTestsFixture.cs
- src/Tests/IntegrationTests/SimpleSqlBuilder.IntegrationTests/SimpleSqlBuilder.IntegrationTests.csproj
- src/Tests/UnitTests/SimpleSqlBuilder.DependencyInjection.UnitTests/SimpleSqlBuilder.DependencyInjection.UnitTests.csproj
- src/Tests/UnitTests/SimpleSqlBuilder.UnitTestHelpers/SimpleSqlBuilder.UnitTestHelpers.csproj
- src/Tests/UnitTests/SimpleSqlBuilder.UnitTests/SimpleSqlBuilder.UnitTests.csproj
- src/version.json
This change adds support for .NET 7 and also updates NuGet packages and documentation.
> .NET 7 support added to the library.

- README.md
- docs/CONTRIBUTING.md
- src/Builder/Directory.Build.props
- src/Builder/SimpleSqlBuilder/Core/Builder.cs
- src/Builder/SimpleSqlBuilder/Core/Handlers/AppendIntactInterpolatedStringHandler.cs
- src/Builder/SimpleSqlBuilder/Core/Handlers/AppendInterpolatedStringHandler.cs
- src/Builder/SimpleSqlBuilder/Core/Handlers/AppendNewLineInterpolatedStringHandler.cs
- src/Builder/SimpleSqlBuilder/Core/SqlBuilder.cs
- src/Tests/Directory.Build.props
- src/Tests/IntegrationTests/SimpleSqlBuilder.IntegrationTests/MSSql/MSSqlTestsFixture.cs
- src/Tests/IntegrationTests/SimpleSqlBuilder.IntegrationTests/PostgreSql/PostgreSqlTestsFixture.cs
- src/Tests/IntegrationTests/SimpleSqlBuilder.IntegrationTests/SimpleSqlBuilder.IntegrationTests.csproj
- src/Tests/UnitTests/SimpleSqlBuilder.UnitTests/Core/BuilderTests.cs
- src/Tests/UnitTests/SimpleSqlBuilder.UnitTests/Core/Handlers/AppendIntactInterpolatedStringHandlerTests.cs
- src/Tests/UnitTests/SimpleSqlBuilder.UnitTests/Core/Handlers/AppendInterpolatedStringHandlerTests.cs
- src/Tests/UnitTests/SimpleSqlBuilder.UnitTests/Core/Handlers/AppendNewLineInterpolatedStringHandlerTests.cs
Changes: 
- Added conditional overloads for Append methods.
- Updated database version for postgres and mssql.
- Updated documentation.
- Code clean-up and optimisations.
> Append methods now have conditional overloads to support conditional statements.

- README.md
Fixed bug with readme icon on NuGet not displaying.
> Fixed bug with readme icon on NuGet not displaying.

- README.md
Fixed incorrect data for benchmark on README file.
> Fixed incorrect data for benchmark on README file.

- README.md
- src/Tests/IntegrationTests/SimpleSqlBuilder.IntegrationTests/Common/ProductHelpers.cs
- src/Tests/UnitTests/SimpleSqlBuilder.DependencyInjection.UnitTests/Core/SimpleBuilderFactoryTests.cs
- src/Tests/UnitTests/SimpleSqlBuilder.DependencyInjection.UnitTests/Extensions/ServiceCollectionExtensionsTests.cs
Fixed issues in README.md and Code clean-up.
> Fixed issues in README.md

- README.md
- src/Tests/IntegrationTests/SimpleSqlBuilder.IntegrationTests/Common/ProductHelpers.cs
- src/Tests/UnitTests/SimpleSqlBuilder.DependencyInjection.UnitTests/Core/SimpleBuilderFactoryTests.cs
- src/Tests/UnitTests/SimpleSqlBuilder.DependencyInjection.UnitTests/Extensions/ServiceCollectionExtensionsTests.cs
Updates to readme and code clean-up.
> README updates

- README.md
- src/Benchmark/SimpleSqlBuilder.BenchMark/SimpleSqlBuilder.BenchMark.csproj
- src/Builder/SimpleSqlBuilder.StrongName/SimpleSqlBuilder.StrongName.csproj
- src/Builder/SimpleSqlBuilder/SimpleSqlBuilder.csproj
- src/Directory.Build.props
- src/Tests/Directory.Build.props
- src/Tests/IntegrationTests/SimpleSqlBuilder.IntegrationTests/SimpleSqlBuilder.IntegrationTests.csproj
> Documentation and NuGet packages update.

- README.md
> Example updates in documentation

- README.md
- src/Benchmark/SimpleSqlBuilder.BenchMark/SimpleSqlBuilder.BenchMark.csproj
- src/Builder/SimpleSqlBuilder.StrongName/SimpleSqlBuilder.StrongName.csproj
- src/Builder/SimpleSqlBuilder/SimpleSqlBuilder.csproj
- src/Directory.Build.props
- src/Tests/Directory.Build.props
- src/Tests/IntegrationTests/SimpleSqlBuilder.IntegrationTests/SimpleSqlBuilder.IntegrationTests.csproj
Documentation and NuGet packages updates.
> Patch release 3.3.*

- .github/ISSUE_TEMPLATE/feature_request.yml
- .github/release.yml
- README.md
- docs/CONTRIBUTING.md
Changes include:
- Improvements to the contributing docs
- Improvements to the feature request template
- Improvements to the release docs template
> Improvements to contributing docs, feature request and release docs templates

- .github/ISSUE_TEMPLATE/feature_request.yml
- .github/release.yml
- README.md
- docs/CONTRIBUTING.md
- src/Benchmark/SimpleSqlBuilder.BenchMark/SimpleSqlBuilder.BenchMark.csproj
- src/Tests/Directory.Build.props
- src/Tests/IntegrationTests/SimpleSqlBuilder.IntegrationTests/SimpleSqlBuilder.IntegrationTests.csproj
Merge documentation updates into main
> Merge documentation updates into main

- .github/workflows/codeql.yml
- README.md
- src/Dapper.SimpleSqlBuilder.sln
This feature enables CodeQL scanning.
> Enable CodeQL scanning

- .github/workflows/codeql.yml
> Improvements to CodeQL action

- .github/workflows/codeql.yml
- README.md
- src/Dapper.SimpleSqlBuilder.sln
> Enable CodeQL in main

- .github/workflows/codeql.yml
- README.md
- src/Benchmark/SimpleSqlBuilder.BenchMark/SimpleSqlBuilder.BenchMark.csproj
- src/Tests/Directory.Build.props
- Updated Nuget packages
- Added on push for codeql.yml
> Updated Nuget packages

- src/Builder/SimpleSqlBuilder/Core/Builder.cs
- src/Builder/SimpleSqlBuilder/Core/SimpleParameterInfo.cs
- src/Tests/Directory.Build.props
Updated code comments to use `<inheritdoc/>`
> chore: Minor documentation updates.

- README.md
- src/Builder/SimpleSqlBuilder/Core/Builder.cs
- src/Builder/SimpleSqlBuilder/Core/SqlBuilder.cs
- src/Builder/SimpleSqlBuilder/Core/SqlFormatter.cs
- src/Builder/SimpleSqlBuilder/FluentBuilder/FluentSqlBuilder.Builders.cs
- src/Builder/SimpleSqlBuilder/FluentBuilder/FluentSqlBuilder.cs
- src/Tests/IntegrationTests/SimpleSqlBuilder.IntegrationTests/MSSql/MSSqlTests.cs
- src/Tests/IntegrationTests/SimpleSqlBuilder.IntegrationTests/MSSql/MSSqlTestsFixture.cs
- src/Tests/IntegrationTests/SimpleSqlBuilder.IntegrationTests/MySql/MySqlTests.cs
- src/Tests/IntegrationTests/SimpleSqlBuilder.IntegrationTests/MySql/MySqlTestsFixture.cs
- src/Tests/IntegrationTests/SimpleSqlBuilder.IntegrationTests/PostgreSql/PostgreSqlTests.cs
- src/Tests/IntegrationTests/SimpleSqlBuilder.IntegrationTests/PostgreSql/PostgreSqlTestsFixture.cs
- src/Tests/UnitTests/SimpleSqlBuilder.UnitTests/Core/BuilderTests.cs
- src/Tests/UnitTests/SimpleSqlBuilder.UnitTests/Core/SqlFormatterTests.cs
- src/version.json
Changes: 
- Added feature to reset the builder
- SqlFormatter code improvements
- Updated unit and integration tests
- Integration tests now use latest docker images
> Implemented functionality to reset the `Builder`

- README.md
Minor typo in one of the code snippets
> Typo in the README.md code example

- src/Benchmark/SimpleSqlBuilder.BenchMark/SimpleSqlBuilder.BenchMark.csproj
- src/Builder/Directory.Build.props
- src/Builder/SimpleSqlBuilder.DependencyInjection/SimpleSqlBuilder.DependencyInjection.csproj
- src/Builder/SimpleSqlBuilder.StrongName/SimpleSqlBuilder.StrongName.csproj
- src/Builder/SimpleSqlBuilder/Core/SqlFormatter.cs
- src/Builder/SimpleSqlBuilder/SimpleSqlBuilder.csproj
- src/Tests/Directory.Build.props
- src/Tests/IntegrationTests/SimpleSqlBuilder.IntegrationTests/SimpleSqlBuilder.IntegrationTests.csproj
- src/Tests/UnitTests/SimpleSqlBuilder.DependencyInjection.UnitTests/SimpleSqlBuilder.DependencyInjection.UnitTests.csproj
Upgraded nuget package version.
- Bumped Dapper version to 2.1.24
- Upgraded other nuget packages in the solution
> Upgraded NuGet packages version. Bumped `Dapper` to version `2.1.24`

- .github/workflows/codeql.yml
- README.md
- src/Benchmark/SimpleSqlBuilder.BenchMark/SimpleSqlBuilder.BenchMark.csproj
- src/Builder/SimpleSqlBuilder.StrongName/SimpleSqlBuilder.StrongName.csproj
- src/Builder/SimpleSqlBuilder/SimpleSqlBuilder.csproj
- src/Tests/Directory.Build.props
- src/Tests/IntegrationTests/SimpleSqlBuilder.IntegrationTests/SimpleSqlBuilder.IntegrationTests.csproj
- src/version.json
Updated NuGet packages and bumped Dapper to version `2.1.28`
> Updated NuGet packages and bumped Dapper to version `2.1.28`

- .github/workflows/ci-cd.yml
> Hotfix: Update ci-cd yaml

- .github/workflows/ci-cd.yml
- README.md
- docs/github-pages/docfx.json
- docs/github-pages/docs/builders/dapper-comparison.md
- docs/github-pages/docs/introduction.md
- src/Benchmark/SimpleSqlBuilder.BenchMark/README.md
- src/Builder/Directory.Build.props
- src/Builder/SimpleSqlBuilder.DependencyInjection/Extensions/ServiceCollectionExtensions.cs
- src/Builder/SimpleSqlBuilder.StrongName/SimpleSqlBuilder.StrongName.csproj
- src/Builder/SimpleSqlBuilder/Core/Builder.cs
- src/Builder/SimpleSqlBuilder/FluentBuilder/IFluentSqlBuilder.cs
- src/Builder/SimpleSqlBuilder/SimpleSqlBuilder.csproj
Improvements to site and code documentation
> Improvements to site and code documentation

- LICENSE.md
> Updated license file

- .github/workflows/ci-cd.yml
Implemented the option to create a sync pull request in workflow
> Implemented the option to create a sync pull request in ci-cd workflow

- .github/workflows/ci-cd.yml
- LICENSE.md
- README.md
- docs/github-pages/docfx.json
- docs/github-pages/docs/builders/dapper-comparison.md
- docs/github-pages/docs/introduction.md
- src/Benchmark/SimpleSqlBuilder.BenchMark/README.md
- src/Benchmark/SimpleSqlBuilder.BenchMark/SimpleSqlBuilder.BenchMark.csproj
- src/Builder/Directory.Build.props
- src/Builder/SimpleSqlBuilder.DependencyInjection/Extensions/ServiceCollectionExtensions.cs
- src/Builder/SimpleSqlBuilder.DependencyInjection/SimpleSqlBuilder.DependencyInjection.csproj
- src/Builder/SimpleSqlBuilder.StrongName/SimpleSqlBuilder.StrongName.csproj
- src/Builder/SimpleSqlBuilder/Core/Builder.cs
- src/Builder/SimpleSqlBuilder/FluentBuilder/IFluentSqlBuilder.cs
- src/Builder/SimpleSqlBuilder/SimpleSqlBuilder.csproj
- src/Dapper.SimpleSqlBuilder.sln
- src/Directory.Build.props
- src/Directory.Packages.props
- src/Tests/Directory.Build.props
- src/Tests/IntegrationTests/SimpleSqlBuilder.IntegrationTests/MySql/MySqlTestsFixture.cs
- src/Tests/IntegrationTests/SimpleSqlBuilder.IntegrationTests/SimpleSqlBuilder.IntegrationTests.csproj
- src/Tests/UnitTests/SimpleSqlBuilder.DependencyInjection.UnitTests/SimpleSqlBuilder.DependencyInjection.UnitTests.csproj
- src/Tests/UnitTests/SimpleSqlBuilder.UnitTestHelpers/SimpleSqlBuilder.UnitTestHelpers.csproj
- src/Tests/UnitTests/SimpleSqlBuilder.UnitTests/SimpleSqlBuilder.UnitTests.csproj
- src/version.json
> Minor Release 3.7.*

- .github/pull_request_template.md
- docs/CONTRIBUTING.md
- docs/github-pages/docs/advanced-features/inner-queries.md
- docs/github-pages/docs/advanced-features/parameter-properties.md
- docs/github-pages/docs/advanced-features/raw-values.md
- docs/github-pages/docs/advanced-features/reusing-parameters.md
- docs/github-pages/docs/builders/builder.md
- docs/github-pages/docs/builders/fluent-builder/conditional-methods.md
- docs/github-pages/docs/builders/fluent-builder/fluent-builder.md
- docs/github-pages/docs/builders/fluent-builder/insert-builder.md
- docs/github-pages/docs/builders/fluent-builder/lower-case-clauses.md
- docs/github-pages/docs/builders/fluent-builder/select-builder.md
- docs/github-pages/docs/builders/fluent-builder/where-filters.md
- docs/github-pages/docs/builders/sql-injection.md
- docs/github-pages/docs/configuration/builder-settings.md
- docs/github-pages/docs/configuration/dependency-injection.md
- docs/github-pages/docs/introduction.md
- docs/github-pages/docs/miscellaneous/performance.md
- docs/github-pages/docs/miscellaneous/release-notes.md
- src/Builder/SimpleSqlBuilder/Core/Handlers/AppendNewLineInterpolatedStringHandler.cs
- src/Dapper.SimpleSqlBuilder.sln
- src/FUNDING.yml
Changes:
- Improved clarity, code examples and fixed grammar issues in documentation.
- Updated pull_request_template.md
- Updated CONTRIBUTING.md
- Added FUNDING.yaml
> Enhanced documentation clarity, updated code examples, and corrected grammatical errors

- README.md
- docs/github-pages/docs/introduction.md
- docs/github-pages/index.md
- src/Builder/Directory.Build.props
- src/Builder/SimpleSqlBuilder.StrongName/SimpleSqlBuilder.StrongName.csproj
- src/Builder/SimpleSqlBuilder/SimpleSqlBuilder.csproj
- Updated README.md, introduction.md, index.md, SimpleSqlBuilder.StrongName.csproj, and SimpleSqlBuilder.csproj to describe Dapper.SimpleSqlBuilder as "simple and performant."
- Added a link to performance documentation in index.md.
- Modified Directory.Build.props to include "orm" in package tags and removed "simple-sql-builder" and "dapper-simple-sql-builder" tags.
> Updated descriptions and tags.

- .github/workflows/ci-cd.yml
- docs/github-pages/_scripts/generate-xrefmap.sh
﻿
Fix for doc-site xref reference.
> Fix for doc-site xref reference.
